### ISSUE TITLE
 buffer.js:378    throw new Error('toString failed')

### ISSUE THREAD

**Issue by arjunkori** [angleman/wgetjs#4]
Hi , I am trying to download about 276 MB of Data But it throws the`**toString failed**` .It always happens with my Node.js Code.My data is downloading perfectly on my local machine. Whenever downloading gets complete it throws **Error: toString failed**.

Here is my Code : 

```
var wget = require('node-wget');

exports.donloadLink = function(mediaLink) {
    console.log("Media Link");
    try {
        wget({
                url: mediaLink,
                dest: // destination path or path with filenname, default is ./             
            },
            function(error, response, body) {
                if (error) {
                    console.log('## ERROR ##' + error); // error encountered 
                } else {
                    console.log('--- body:');
                    console.log(body); // content of package 
                }
            }
        );
    } catch (ex) {
        console.log('Exception :' + ex)
    }
}
```

Error Is :

```
    Error: toString failed
    at Buffer.toString (buffer.js:378:11)
```

**Comment by angleman** [comment]
@arjunkori, I suspect it is related to available memory of the system it is running on. That said, wgetjs is a high level wrapper around the `request` module which does the heavy lifting. Perhaps the `request` team can assist. Hope this helps :-)
